### PR TITLE
Use connect library for static file serving.

### PR DESCRIPTION
**Pull request by rhyolight**
Connect.js is a very simple extension to the Node.js http functions that allow the usage of "middleware" and includes several useful middlewares. In this PR, I've installed Connect.js and started using its static file serving middleware instead of a hand-written one. 

I also moved all the static files into a `static` directory, which is pretty standard for Node.js apps.

### CODE REVIEW

**Comment by iandanforth** [comment]
Github says there are conflicts that need to be resolved before this can be merged.

**Comment by rhyolight** [comment]
Ok, merged in master.

**Comment by jefffohl** [comment]
@iandanforth - did you mean to close this PR without merging?

**Comment by iandanforth** [comment]
@jefffohl Yes. I decided the static/ convention was burying the examples too much. Also the connect.js is a bit more than this project needs. I expect anyone using this to get by with webserver.js or use their own node code. It's really only there as the most basic/barebones support to run the examples.

**Comment by jefffohl** [comment]
Ah, OK. Thanks for the clarification.

**Pull request closed without merging**
